version: '3'

networks:
  rabbitmq:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.8.16-management
    networks:
      - rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
#    volumes:
#      - ./rabbitmq/config/config.json:/tmp/rabbitmq/config.json
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
#      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/tmp/rabbitmq/config.json"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5


  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    networks:
      - rabbitmq
    container_name: consumer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    networks:
      - rabbitmq
    container_name: producer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest